[tool.commitizen]

version = "0.0.0"
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "pep440"
version_provider = "commitizen"
update_changelog_on_bump = true
major_version_zero = true
version_files = [
    ".cz.toml:version"
]
